pipeline {
    agent {
        docker { image 'node:16-alpine' }
    }
    stages {
        stage('Test') {
            steps {
                echo 'Running inside Docker container...'
                sh 'node --version'
            }
        }
    }
}


